version: '3.7'
services:

  #PHP Service
  b201-php:
    build:
      context: .
      dockerfile: Dockerfile
    image: app-php
    container_name: b201-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /
    volumes:
      - ./:/var/www      
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  b201-nginx:
    image: nginx:alpine
    container_name: b201-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "90:80"
      - "543:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  b201-mysql:
    image: mysql:8.0.15
    container_name: b201-db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: b201
      MYSQL_ROOT_PASSWORD: "12345678"            
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
